version: '3'

services:
  app:
    container_name: w_app
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile_app
    volumes:
      - ./data:/var/www/html/app
    links:
      - mysql
  nginx:
    container_name: nginx
    image: nginx:1.21.6
    ports:
      - "80:80"
    volumes:
      - ./nginx_conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/public:/var/www/html/app/public
  mysql:
    container_name: w_mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'quarterly_summary'
    ports:
      - "8002:3306"
    command:
      [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]
  pma:
    container_name: w_pma
    image: phpmyadmin:5.2
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      PMA_HOST: mysql
    links:
      - mysql
    ports:
      - "9191:80"
