FROM php:8.1-fpm-buster

WORKDIR /var/www/html/app
# Install PHP extensions and PECL modules.
RUN buildDeps=" \
    default-libmysqlclient-dev \
    libbz2-dev \
    " \
    runtimeDeps=" \
    curl \
    git \
    libzip-dev \
    libfreetype6-dev \
    libicu-dev \
    libjpeg-dev \
    libpng-dev \
    libpq-dev \
    libxml2-dev \
    libonig-dev \
    libldap2-dev \
    " \
    && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y $buildDeps $runtimeDeps \
    && docker-php-ext-install bcmath bz2 calendar iconv intl mbstring exif mysqli pdo_mysql pdo_pgsql zip\
    && docker-php-ext-configure gd --with-freetype=/usr/include/ --with-jpeg=/usr/include/ \
    && docker-php-ext-install gd \
    && apt-get purge -y --auto-remove $buildDeps \
    && rm -r /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y libgmp-dev
RUN docker-php-ext-install gmp
RUN usermod -u 1000 www-data

# Install Composer.
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && ln -s $(composer config --global home) /root/composer
ENV PATH $PATH:/root/composer/vendor/bin
